<a href="https://colab.research.google.com/github/SujitVarma299/2311cs020685/blob/main/Data_cleaning_imputations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
data={
    'square_feet_area':[8500,9600,np.nan,11250,np.nan,9550,14260,np.nan,13830, 11500],
    'Year_built':[2003,1967,2001,np.nan,1998,2000,2005,1978,1950,np.nan],
    'overall_condition':[5,8,6,7,np.nan,7,8,6,np.nan,7],
    'ready_to_momve':['Yes','No','No',np.nan,'No',np.nan,'No','Yes','No','Yes'],
    'Sale_price':[200000,180000,215000,250000,210000,190000,230000,225000,220000,240000]
}
df=pd.DataFrame(data)
print("Original DataFrame: ")
df

Original DataFrame:

   square_feet_area  Year_built  overall_condition ready_to_momve  Sale_price
0            8500.0      2003.0                5.0            Yes      200000
1            9600.0      1967.0                8.0             No      180000
2               NaN      2001.0                6.0             No      215000
3           11250.0         NaN                7.0            NaN      250000
4               NaN      1998.0                NaN             No      210000
5            9550.0      2000.0                7.0            NaN      190000
6           14260.0      2005.0                8.0             No      230000
7               NaN      1978.0                6.0            Yes      225000
8           13830.0      1950.0                NaN             No      220000
9           11500.0         NaN                7.0            Yes      240000

In [8]:
import pandas as pd
import numpy as np

data = {
    'square_feet_area': [8500, 9600, np.nan, 11250, np.nan, 9550, 14260, np.nan, 13830, 11500],
    'Year_built': [2003, 1967, 2001, np.nan, 1998, 2000, 2005, 1978, 1950, np.nan],
    'overall_condition': [5, 8, 6, 7, np.nan, 7, 8, 6, np.nan, 7],
    'ready_to_momve': ['Yes', 'No', 'No', np.nan, 'No', np.nan, 'No', 'Yes', 'No', 'Yes'],
    'Sale_price': [200000, 180000, 215000, 250000, 210000, 190000, 230000, 225000, 220000, 240000]
}

df = pd.DataFrame(data)
print("Original DataFrame: ")
print(df)

df['square_feet_area'].fillna(df['square_feet_area'].mean(), inplace=True)
df['Year_built'].fillna(df['Year_built'].mean(), inplace=True)
df['overall_condition'].fillna(df['overall_condition'].mean(), inplace=True)
df['ready_to_momve'].fillna(df['ready_to_momve'].mode()[0], inplace=True)
print("\nDataFrame after handling missing values: ")
print(df)

Original DataFrame:
   square_feet_area  Year_built  overall_condition ready_to_momve  Sale_price
0            8500.0      2003.0                5.0            Yes      200000
1            9600.0      1967.0                8.0             No      180000
2               NaN      2001.0                6.0             No      215000
3           11250.0         NaN                7.0            NaN      250000
4               NaN      1998.0                NaN             No      210000
5            9550.0      2000.0                7.0            NaN      190000
6           14260.0      2005.0                8.0             No      230000
7               NaN      1978.0                6.0            Yes      225000
8           13830.0      1950.0                NaN             No      220000
9           11500.0         NaN                7.0            Yes      240000

DataFrame after handling missing values:
   square_feet_area  Year_built  overall_condition ready_to_momve  Sale_price
0       8500.000000     2003.00               5.00            Yes      200000
1       9600.000000     1967.00               8.00             No      180000
2      11212.857143     2001.00               6.00             No      215000
3      11250.000000     1987.75               7.00             No      250000
4      11212.857143     1998.00               6.75             No      210000
5       9550.000000     2000.00               7.00             No      190000
6      14260.000000     2005.00               8.00             No      230000
7      11212.857143     1978.00               6.00            Yes      225000
8      13830.000000     1950.00               6.75             No      220000
9      11500.000000     1987.75               7.00            Yes      240000

<ipython-input-8-7fe266c4337e>:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['square_feet_area'].fillna(df['square_feet_area'].mean(), inplace=True)
<ipython-input-8-7fe266c4337e>:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Year_built'].fillna(df['Year_built'].mean(), inplace=True)
<ipython-input-8-7fe266c4337e>:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['overall_condition'].fillna(df['overall_condition'].mean(), inplace=True)
<ipython-input-8-7fe266c4337e>:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ready_to_momve'].fillna(df['ready_to_momve'].mode()[0], inplace=True)

In [9]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
data = {
    'square_feet_area': [8500, 9600, np.nan, 11250, np.nan, 9550, 14260, np.nan, 13830, 11500],
    'Year_built': [2003, 1967, 2001, np.nan, 1998, 2000, 2005, 1978, 1950, np.nan],
    'overall_condition': [5, 8, 6, 7, np.nan, 7, 8, 6, np.nan, 7],
    'ready_to_momve': ['Yes', 'No', 'No', np.nan, 'No', np.nan, 'No', 'Yes', 'No', 'Yes'],
    'Sale_price': [200000, 180000, 215000, 250000, 210000, 190000, 230000, 225000, 220000, 240000]
}
df = pd.DataFrame(data)
numeric_imputer = SimpleImputer(strategy='mean')
df[['square_feet_area', 'Year_built', 'overall_condition']] = numeric_imputer.fit_transform(
    df[['square_feet_area', 'Year_built', 'overall_condition']]
)
categorical_imputer = SimpleImputer(strategy='most_frequent')
df[['ready_to_momve']] = categorical_imputer.fit_transform(df[['ready_to_momve']])

print(df)

   square_feet_area  Year_built  overall_condition ready_to_momve  Sale_price
0       8500.000000     2003.00               5.00            Yes      200000
1       9600.000000     1967.00               8.00             No      180000
2      11212.857143     2001.00               6.00             No      215000
3      11250.000000     1987.75               7.00             No      250000
4      11212.857143     1998.00               6.75             No      210000
5       9550.000000     2000.00               7.00             No      190000
6      14260.000000     2005.00               8.00             No      230000
7      11212.857143     1978.00               6.00            Yes      225000
8      13830.000000     1950.00               6.75             No      220000
9      11500.000000     1987.75               7.00            Yes      240000