<a href="https://colab.research.google.com/github/SujitVarma299/2311cs020685/blob/main/Python_Day_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

# Sample data for sales transactions
sales_data = {
    'Date': ['2023-01-02', '2023-01-03', '2023-01-03', '2023-01-20', '2023-01-04', '2023-01-17',
             '2023-01-14', '2023-01-07', '2023-01-11', '2023-01-01', '2023-01-19', '2023-01-12',
             '2023-01-09', '2023-01-10', '2023-01-08', '2023-01-05', '2023-01-15', '2023-01-18',
             '2023-01-13', '2023-01-16'],
    'Product': ['Tablet', 'Laptop', 'Tablet', 'Tablet', 'Laptop', 'Tablet', 'Keyboard', 'Smartphone',
                'Smartphone', 'Laptop', 'Monitor', 'Laptop', 'Monitor', 'Smartphone', 'Laptop',
                'Keyboard', 'Tablet', 'Monitor', 'Tablet', 'Tablet'],
    'Region': ['East', 'North', 'East', 'North', 'West', 'North', 'East', 'East', 'West', 'North',
               'North', 'West', 'North', 'North', 'East', 'North', 'North', 'West', 'West', 'South'],
    'Sales': [1061.81, 1926.07, 1597.99, 1397.99, 734.03, 733.99, 587.13, 1799.26, 1401.67, 1562.11,
              530.88, 1954.86, 1748.66, 818.51, 772.74, 775.11, 956.36, 1287.13, 1147.92, 936.84],
    'Profit': [236.12, 246.34, 253.17, 242.23, 140.36, 188.66, 82.16, 364.97, 306.24, 170.72,
               117.59, 262.16, 197.62, 237.19, 226.51, 202.83, 153.9, 153.86, 271.88, 176.15],
    'Quantity': [7, 8, 3, 4, 4, 4, 9, 4, 4, 6, 5, 6, 6, 2, 3, 4, 8, 6, 9, 8]
}

# Convert data into DataFrame
sales_df = pd.DataFrame(sales_data)

# Data Filtering
# Extract all rows where sales are greater than 1000
high_sales_df = sales_df[sales_df['Sales'] > 1000]
print("Rows where sales are greater than 1000:")
print(high_sales_df)

# Find all sales records for a specific region (e.g., "East")
east_sales_df = sales_df[sales_df['Region'] == 'East']
print("\nSales records for the 'East' region:")
print(east_sales_df)

# Data Processing
# Add a new column, Profit_Per_Unit, calculated as Profit / Quantity
sales_df['Profit_Per_Unit'] = sales_df['Profit'] / sales_df['Quantity']
print("\nData with Profit_Per_Unit column added:")
print(sales_df)

# Create another column, High_Sales, which labels rows as Yes if Sales > 1000, else No
sales_df['High_Sales'] = sales_df['Sales'].apply(lambda x: 'Yes' if x > 1000 else 'No')
print("\nData with High_Sales column added:")
print(sales_df)

Rows where sales are greater than 1000:
          Date     Product Region    Sales  Profit  Quantity
0   2023-01-02      Tablet   East  1061.81  236.12         7
1   2023-01-03      Laptop  North  1926.07  246.34         8
2   2023-01-03      Tablet   East  1597.99  253.17         3
3   2023-01-20      Tablet  North  1397.99  242.23         4
7   2023-01-07  Smartphone   East  1799.26  364.97         4
8   2023-01-11  Smartphone   West  1401.67  306.24         4
9   2023-01-01      Laptop  North  1562.11  170.72         6
11  2023-01-12      Laptop   West  1954.86  262.16         6
12  2023-01-09     Monitor  North  1748.66  197.62         6
17  2023-01-18     Monitor   West  1287.13  153.86         6
18  2023-01-13      Tablet   West  1147.92  271.88         9

Sales records for the 'East' region:
          Date     Product Region    Sales  Profit  Quantity
0   2023-01-02      Tablet   East  1061.81  236.12         7
2   2023-01-03      Tablet   East  1597.99  253.17         3
6   2023-01-14    Keyboard   East   587.13   82.16         9
7   2023-01-07  Smartphone   East  1799.26  364.97         4
14  2023-01-08      Laptop   East   772.74  226.51         3

Data with Profit_Per_Unit column added:
          Date     Product Region    Sales  Profit  Quantity  Profit_Per_Unit
0   2023-01-02      Tablet   East  1061.81  236.12         7        33.731429
1   2023-01-03      Laptop  North  1926.07  246.34         8        30.792500
2   2023-01-03      Tablet   East  1597.99  253.17         3        84.390000
3   2023-01-20      Tablet  North  1397.99  242.23         4        60.557500
4   2023-01-04      Laptop   West   734.03  140.36         4        35.090000
5   2023-01-17      Tablet  North   733.99  188.66         4        47.165000
6   2023-01-14    Keyboard   East   587.13   82.16         9         9.128889
7   2023-01-07  Smartphone   East  1799.26  364.97         4        91.242500
8   2023-01-11  Smartphone   West  1401.67  306.24         4        76.560000
9   2023-01-01      Laptop  North  1562.11  170.72         6        28.453333
10  2023-01-19     Monitor  North   530.88  117.59         5        23.518000
11  2023-01-12      Laptop   West  1954.86  262.16         6        43.693333
12  2023-01-09     Monitor  North  1748.66  197.62         6        32.936667
13  2023-01-10  Smartphone  North   818.51  237.19         2       118.595000
14  2023-01-08      Laptop   East   772.74  226.51         3        75.503333
15  2023-01-05    Keyboard  North   775.11  202.83         4        50.707500
16  2023-01-15      Tablet  North   956.36  153.90         8        19.237500
17  2023-01-18     Monitor   West  1287.13  153.86         6        25.643333
18  2023-01-13      Tablet   West  1147.92  271.88         9        30.208889
19  2023-01-16      Tablet  South   936.84  176.15         8        22.018750

Data with High_Sales column added:
          Date     Product Region    Sales  Profit  Quantity  Profit_Per_Unit  \
0   2023-01-02      Tablet   East  1061.81  236.12         7        33.731429
1   2023-01-03      Laptop  North  1926.07  246.34         8        30.792500
2   2023-01-03      Tablet   East  1597.99  253.17         3        84.390000
3   2023-01-20      Tablet  North  1397.99  242.23         4        60.557500
4   2023-01-04      Laptop   West   734.03  140.36         4        35.090000
5   2023-01-17      Tablet  North   733.99  188.66         4        47.165000
6   2023-01-14    Keyboard   East   587.13   82.16         9         9.128889
7   2023-01-07  Smartphone   East  1799.26  364.97         4        91.242500
8   2023-01-11  Smartphone   West  1401.67  306.24         4        76.560000
9   2023-01-01      Laptop  North  1562.11  170.72         6        28.453333
10  2023-01-19     Monitor  North   530.88  117.59         5        23.518000
11  2023-01-12      Laptop   West  1954.86  262.16         6        43.693333
12  2023-01-09     Monitor  North  1748.66  197.62         6        32.936667
13  2023-01-10  Smartphone  North   818.51  237.19         2       118.595000
14  2023-01-08      Laptop   East   772.74  226.51         3        75.503333
15  2023-01-05    Keyboard  North   775.11  202.83         4        50.707500
16  2023-01-15      Tablet  North   956.36  153.90         8        19.237500
17  2023-01-18     Monitor   West  1287.13  153.86         6        25.643333
18  2023-01-13      Tablet   West  1147.92  271.88         9        30.208889
19  2023-01-16      Tablet  South   936.84  176.15         8        22.018750

   High_Sales
0         Yes
1         Yes
2         Yes
3         Yes
4          No
5          No
6          No
7         Yes
8         Yes
9         Yes
10         No
11        Yes
12        Yes
13         No
14         No
15         No
16         No
17        Yes
18        Yes
19         No